#!/bin/bash
# wimip - What Is My IP
# Displays your public IP, local IP, and location

printf "\033[1;36m%-10s\033[0m : %s\n" "Public IP" "$(curl -s ifconfig.me)"
printf "\033[1;36m%-10s\033[0m : %s\n" "Local IP" "$(hostname -I | awk '{print $1}')"
printf "\033[1;36m%-10s\033[0m : %s\n" "Location" "$(curl -s ipinfo.io/city), $(curl -s ipinfo.io/region)"
